### ISSUE TITLE
Server Disconnects Player on Snap

### ISSUE THREAD

**Issue by JLUsr** [LlamaramaTeam/SnapStone#1]
When snapping the server will disconnect the player.

Server View
`[Netty Epoll Server IO #0/ERROR]: Error receiving packet 95
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@50cae09d' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.9) ~[?:?]
        at net.minecraft.network.PacketByteBuf.writeRegistryValue(PacketByteBuf:147) ~[?:?]
        at net.minecraft.network.packet.s2c.play.PlaySoundFromEntityS2CPacket.write(PlaySoundFromEntityS2CPacket:40) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder:45) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder:14) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

Player View
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@50cae09d' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]`
![ClientSide](https://user-images.githubusercontent.com/47650360/189475237-4c0d4d0d-972f-4b90-ab27-0cc420e417e4.png)

**Comment by 0xJoeMama** [comment]
Could you provide the versions you are using? Minecraft, SnapStone and your loader/API version.

**Comment by 0xJoeMama** [comment]
Actually, don't worry about it. I have located the issue. Expect a new release today!
